name: Pubgrade


on:
  repository_dispatch:
    types: [sign-image]  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.event.client_payload.docker_username }}
        password: ${{ github.event.client_payload.docker_password }}


    - name: Pull Image
      run: docker pull ${{ github.event.client_payload.pull_tag }}
      
    - name: Tag changed
      run: docker tag ${{ github.event.client_payload.pull_tag }} ${{ github.event.client_payload.push_tag }}
      
    - name: Sign and push docker image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: ${{ github.event.client_payload.push_tag }}
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
      
    - name: Build the Docker image
      run: docker push ${{ github.event.client_payload.push_tag }}
