name: Pubgrade


on:
  repository_dispatch:
    types: [sign-image]  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.event.client_payload.docker_username }}
        password: ${{ github.event.client_payload.docker_password }}
          
    - name: Pull Image
      run: docker pull ${{ github.event.client_payload.pull_tag }}

    - name: Enable Docker Content Trust
      run: echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV
      

    - name: Decrypt Docker signing key
      run: |
        echo "${{ secrets.DOCKER_PRIVATE_KEY }}" > signing-key.enc
        echo "${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}" | openssl aes-256-cbc -d -in signing-key.enc -out signing-key.key -pass stdin
        chmod 600 signing-key.key
    
    - name: Import Docker signing key
      run: |
        docker trust key load signing-key.key
      
    - name: Tag changed
      run: docker tag ${{ github.event.client_payload.pull_tag }} ${{ github.event.client_payload.push_tag }}

    - name: Sign and Push Docker Image with DCT
      run: |
          # Push the signed image
          docker push ${{ github.event.client_payload.push_tag }}
      
    - name: Sign and push docker image
      uses: sudo-bot/action-docker-sign@latest
      with:
        image-ref: ${{ github.event.client_payload.push_tag }}
        private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
        private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
        private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
      
    - name: Build the Docker image
      run: docker push ${{ github.event.client_payload.push_tag }}
