name: Pubgrade


on:
  repository_dispatch:
    types: [sign-image]  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.event.client_payload.docker_username }}
        password: ${{ github.event.client_payload.docker_password }}
          
    - name: Pull Image
      run: docker pull ${{ github.event.client_payload.pull_tag }}

    - name: Enable Docker Content Trust
      run: echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV

    - name: Decrypt and Import Signing Key
      run: |
        echo "${{ secrets.DOCKER_PRIVATE_KEY }}" > signing-key.key
        chmod 600 signing-key.key
        notary key import signing-key.key --role targets/releases

    - name: Add Delegation Key
      run: |
        notary delegation add docker.io/akash7778/sampleapp targets/releases signing-key.key
        notary publish docker.io/akash7778/sampleapp

    # - name: Decrypt and Import Docker signing key
    #   run: |
    #     echo "${{ secrets.DOCKER_PRIVATE_KEY }}" > signing-key.key
    #     chmod 600 signing-key.key
    #     docker trust key load signing-key.key << EOF
    #     ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
    #     EOF
    
    - name: Tag changed
      run: docker tag ${{ github.event.client_payload.pull_tag }} ${{ github.event.client_payload.push_tag }}
      
    - name: Sign the Docker Image
      run: |
        export DOCKER_CONTENT_TRUST=1
        docker trust sign ${{ github.event.client_payload.push_tag }}
        
    - name: Push the Docker image
      run: docker push ${{ github.event.client_payload.push_tag }}
